#!/bin/sh
bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor HDMI-1-1 -d 1 2 3 4 5 6 7 8 9
bspc config border_width 2
bspc config window_gap 0
bspc config normal_border_color "#504945"
bspc config active_border_color "#fabd2f"
bspc config focused_border_color "#8ec07c"

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus any

bspc rule -a emacs desktop=^2
bspc rule -a discord desktop=^4 follow=off
bspc rule -a deadbeef desktop=^9
bspc rule -a Emacs state=tiled

~/.config/eww/start.sh &
sleep 1
~/.config/autostart.sh &

# g="$(bspc config window_gap)"
# [[ "$g" -gt 0 ]] && for p in top bottom left right; do
#     bspc config "${p}_padding" "-${g}"
#     bspc config "${p}_monocle_padding" "$g"
# done

