#!/bin/sh
eww open status
bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width 2
bspc config window_gap 8
bspc config normal_border_color "#504945"
bspc config active_border_color "#fabd2f"
bspc config focused_border_color "#8ec07c"

bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config click_to_focus any

bspc rule -a discord desktop=^4 follow=off
bspc rule -a deadbeef desktop=^9

g="$(bspc config window_gap)"
[[ "$g" -gt 0 ]] && for p in top bottom left right; do
    bspc config "${p}_padding" "-${g}"
    bspc config "${p}_monocle_padding" "$g"
done
